sudo: required
services:
  - docker

before_install:
  - docker build -t howardhs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run howardhs/react-test yarn run test -- --coverage

after_success:
  - docker build -t howardhs/fibonacci-client ./client
  - docker build -t howardhs/fibonacci-nginx ./nginx
  - docker build -t howardhs/fibonacci-server ./server
  - docker build -t howardhs/fibonacci-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push howardhs/fibonacci-client
  - docker push howardhs/fibonacci-nginx
  - docker push howardhs/fibonacci-server
  - docker push howardhs/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "fibonacci-app"
  env: "FibonacciApp-env"
  bucket-name: "elasticbeanstalk-ap-southeast-1-996604352733"
  bucket_path: "fibonacci-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"